### ISSUE TITLE
cant install jupyterlab plotly extension , running Windows 11 pro

### ISSUE THREAD

**Issue by StevenOshry** [PacktPublishing/Interactive-Dashboards-and-Data-Apps-with-Plotly-and-Dash#4]
Hi;  I am following the book and on page 5, setting up envronment, you say to run command: upyter labextension install jupyterlab-plotly@4.14.1.  

I get the following error:

Traceback (most recent call last):
  File "c:\users\steve\onedrive\documents\interactive_dashboards_dash_book\dash_project\lib\site-packages\jupyter_server\services\sessions\sessionmanager.py", line 9, in <module>
    import sqlite3
  File "C:\Users\steve\anaconda3\pkgs\python-3.8.5-h5fd99cc_1\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "C:\Users\steve\anaconda3\pkgs\python-3.8.5-h5fd99cc_1\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed while importing _sqlite3: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\steve\anaconda3\pkgs\python-3.8.5-h5fd99cc_1\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\steve\anaconda3\pkgs\python-3.8.5-h5fd99cc_1\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\steve\OneDrive\Documents\Interactive_dashboards_dash_book\dash_project\Scripts\jupyter-labextension.EXE\__main__.py", line 4, in <module>
  File "c:\users\steve\onedrive\documents\interactive_dashboards_dash_book\dash_project\lib\site-packages\jupyterlab\__init__.py", line 7, in <module>
    from .labapp import LabApp
  File "c:\users\steve\onedrive\documents\interactive_dashboards_dash_book\dash_project\lib\site-packages\jupyterlab\labapp.py", line 15, in <module>
    from jupyterlab_server import slugify, WORKSPACE_EXTENSION
  File "c:\users\steve\onedrive\documents\interactive_dashboards_dash_book\dash_project\lib\site-packages\jupyterlab_server\__init__.py", line 4, in <module>
    from .app import LabServerApp
  File "c:\users\steve\onedrive\documents\interactive_dashboards_dash_book\dash_project\lib\site-packages\jupyterlab_server\app.py", line 11, in <module>
    from jupyter_server.extension.application import ExtensionApp, ExtensionAppJinjaMixin
  File "c:\users\steve\onedrive\documents\interactive_dashboards_dash_book\dash_project\lib\site-packages\jupyter_server\extension\application.py", line 21, in <module>
    from jupyter_server.serverapp import ServerApp
  File "c:\users\steve\onedrive\documents\interactive_dashboards_dash_book\dash_project\lib\site-packages\jupyter_server\serverapp.py", line 80, in <module>
    from .services.sessions.sessionmanager import SessionManager
  File "c:\users\steve\onedrive\documents\interactive_dashboards_dash_book\dash_project\lib\site-packages\jupyter_server\services\sessions\sessionmanager.py", line 12, in <module>
    from pysqlite2 import dbapi2 as sqlite3
ModuleNotFoundError: No module named 'pysqlite2'

**Comment by eliasdabbas** [comment]
Thanks for reporting @StevenOshry 

I can share the following remarks/thoughts: 

1. When installing the jupyter lab extension with `jupyter labextension install jupyterlab-plotly@4.14.1`, plesae make sure that the version number (4.14.1 in this case) matches your plotly version (which is now at v5), they just need to match.
2. It seems you are running from anaconda. I don't think it should cause a problem, but maybe try with pure Python, and check that it works. 
3. Did you install the requirements with `pip install -r requirements.txt` and got no issues?
4. Did you activate the virtual environment and run all commands from there?
5. If so, sometimes you might need to deactivate, and then activate the virtual environment for certain changes to take effect.

I hope this helps, and please let me know how it goes.

**Comment by StevenOshry** [comment]
Hi Elias: 

Thank you so much for getting back to me.  I decided to try uninstalling Python 3.10 and switching to python 3.9.9.  It worked!! Now I am looking forward to working through your book.  Virtual environments are great but I think we also need to take into account the python version that we are building the virtual environment on.  

Thanks again!!

**Comment by StevenOshry** [comment]
Hi Elias: I tried uninstalling Python 3.10 and installing 3.9.9 and it worked!!  Thank you! Steve Sent from Mail for Windows From: Steven OshrySent: Saturday, June 11, 2022 1:12 PMTo: PacktPublishing/Interactive-Dashboards-and-Data-Apps-with-Plotly-and-DashSubject: RE: [PacktPublishing/Interactive-Dashboards-and-Data-Apps-with-Plotly-and-Dash] cant install jupyterlab plotly extension , running Windows 11 pro (Issue #4) Hi Elias: Thank you so much for your reply.  When I run “Pip install requirements.txt”, I get the error below.  I am running Python 3.10.  Should I switch to a different version? Thank you  Sent from Mail for Windows From: Elias DabbasSent: Monday, June 6, 2022 9:53 AMTo: PacktPublishing/Interactive-Dashboards-and-Data-Apps-with-Plotly-and-DashCc: Steven Oshry; MentionSubject: Re: [PacktPublishing/Interactive-Dashboards-and-Data-Apps-with-Plotly-and-Dash] cant install jupyterlab plotly extension , running Windows 11 pro (Issue #4) Thanks for reporting @StevenOshryI can share the following remarks/thoughts:When installing the jupyter lab extension with jupyter labextension install ***@***.***, plesae make sure that the version number (4.14.1 in this case) matches your plotly version (which is now at v5), they just need to match.It seems you are running from anaconda. I don't think it should cause a problem, but maybe try with pure Python, and check that it works.Did you install the requirements with pip install -r requirements.txt and got no issues?Did you activate the virtual environment and run all commands from there?If so, sometimes you might need to deactivate, and then activate the virtual environment for certain changes to take effect.I hope this helps, and please let me know how it goes.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by eliasdabbas** [comment]
Thanks for letting me know @StevenOshry and glad it worked!
Interesting to know that the Python version change made it work. Not sure what specifically caused the problem.

Anyway, it worked!

Hope you like the book, and looking forward to seeing the dashboards that you will build :)
